import os
import sys
import random
import subprocess
import argparse
import pandas as pd
import numpy as np

from rdkit import Chem
from rdkit.Chem import AllChem
from tempfile import NamedTemporaryFile
from ase import Atoms
from ase.io import write
from openbabel import pybel


def make_branched(smiles_bank=None, working_dir=".",
                  copolymer=False, max_atoms=200, n_branches=3):
    """
    Returns a SMILES of a star polymer with n_branches arms and less than 200 atoms
    """
    all_smiles = pd.read_csv(os.path.join(working_dir, smiles_bank), header=None)[0]
    smiles_list = [random.choice(all_smiles)]
    mol = Chem.MolFromSmiles(smiles_list[0])
    charged = is_charged(mol)
    while charged:
        smiles_list = [random.choice(all_smiles)]
        mol = Chem.MolFromSmiles(smiles_list[0])
        charged = is_charged(mol)
    
    if copolymer:
        n_copoly = random.randint(1, 3)
        for i in range(n_copoly):
            smiles = random.choice(all_smiles)
            mol = Chem.MolFromSmiles(smiles)
            if smiles not in smiles_list:
                smiles_list.append(smiles)
                
    # select a SMILES for the branch construction
    branch_smiles = random.choice(smiles_list)
    growing_smiles = make_branching_point(branch_smiles, n_stars=n_branches)
    growing_smiles = relabel_stars(growing_smiles)

    def grow_chain(smiles_list, growing_smiles):
        growing_mol = Chem.AddHs(Chem.MolFromSmiles(growing_smiles))
        growing_smarts = "[Au:1][*:2].[*:3][Au:4]>>[*:2][*:3].[Au:1][Au:4]"

        while growing_mol.GetNumAtoms() < (max_atoms - n_branches):
            smiles = random.choice(smiles_list)
            add_mol = Chem.AddHs(Chem.MolFromSmiles(relabel_stars(smiles)))
            growing_mol = Chem.AddHs(Chem.MolFromSmiles(Chem.MolToSmiles(growing_mol)))
            
            if add_mol is None:
                continue
                    
            grow_rxn = AllChem.ReactionFromSmarts(growing_smarts)
            products = grow_rxn.RunReactants([growing_mol, add_mol])
            growing_mol = random.choice(products)[0]
        return growing_mol
    
    growing_mol = grow_chain(smiles_list, growing_smiles)
    total_charge = np.abs(Chem.GetFormalCharge(growing_mol))
    while total_charge > 3:
        growing_mol = grow_chain(smiles_list, growing_smiles)
        total_charge = np.abs(Chem.GetFormalCharge(growing_mol))

    # cap with hydrogen
    capping_smarts = "[Au:1][*:2].[H:3]>>[H:3][*:2].[Au:1]"
    h_mol = Chem.MolFromSmiles("[H]")
    
    cap_rxn = AllChem.ReactionFromSmarts(capping_smarts)
    products = cap_rxn.RunReactants([growing_mol, h_mol])
    while products:
        growing_mol = random.choice(products)[0]
        products = cap_rxn.RunReactants([growing_mol, h_mol])
        
    return Chem.MolToSmiles(growing_mol)
   
def make_branching_point(smiles, n_stars=3):
    """
    Returns a repeat unit with n_stars connection points for branching
    """
    smiles = smiles.replace('[*]', '*').replace('/', '').replace('\\', '')
    if smiles[0] == "*":
        smiles = smiles[1] + "(*)" + smiles[2:]
    
    n_to_start = len([i for i, c in enumerate(smiles) if c == '*'])
    h_smiles = Chem.MolToSmiles(Chem.AddHs(Chem.MolFromSmiles(smiles)))

    while n_to_start < n_stars:
        try:
            H_idx_to_replace = random.choice([i for i, c in enumerate(h_smiles) if c == 'H'])
        except IndexError: # necessary for fluoropolymers
            H_idx_to_replace = random.choice([i for i, c in enumerate(h_smiles) if c == 'F'])
            
        smiles = h_smiles[:H_idx_to_replace] + '*' + h_smiles[H_idx_to_replace+1:]
        smiles = smiles.replace('[*]', '*')
        
        n_to_start = len([i for i, c in enumerate(smiles) if c == '*'])
        h_smiles = Chem.MolToSmiles(Chem.AddHs(Chem.MolFromSmiles(smiles)))

    return smiles

def run_loqi(smiles, index, working_dir, loqi_path, n_confs=100, batch_size=8):
    """
    Returns path to sdf generated by LoQI conformer program
    """
    sdf_out = os.path.join(working_dir, "sdfs/", f"run_{index}.sdf")

    try: 
        subprocess.run(
            [
                sys.executable, 
                f"{loqi_path}/scripts/sample_conformers.py",
                "--config", f"{loqi_path}/scripts/conf/loqi/loqi.yaml",
                "--ckpt", f"{loqi_path}/LoQI_data/loqi.ckpt",
                "--input", smiles,
                "--output", sdf_out,
                "--n_confs", f"{n_confs}",
                "--batch_size", f"{batch_size}",
                "--skip_eval", True,
            ],
            check=True,
        )
    except subprocess.CalledProcessError:
        pass
    
    return sdf_out

def prune_confs(sdf_file, smiles, output_path, n_samples=10):
    """
    Saves connected n_samples conformers from LoQI output
    """
    basename = os.path.splitext(os.path.basename(sdf_file))[0]
    supplier = Chem.SDMolSupplier(sdf_file, sanitize=False)

    mol = Chem.Mol(supplier[0])
    for s in list(supplier)[1:]:
        mol.AddConformer(s.GetConformer(), assignId=True)
    
    rmslist = []
    AllChem.AlignMolConformers(mol, RMSlist=rmslist)
    
    atoms_list = []
    og_mol = Chem.MolFromSmiles(smiles)
    for i, conf in enumerate(mol.GetConformers()):
        symbols = [atom.GetSymbol() for atom in mol.GetAtoms()]
        positions = [[conf.GetAtomPosition(i).x,
                      conf.GetAtomPosition(i).y,
                      conf.GetAtomPosition(i).z] for i in range(mol.GetNumAtoms())]
        
        atoms = Atoms(symbols=symbols, positions=positions)
        if has_right_connectivity(atoms, og_mol):
            atoms_list.append(atoms)

    if not atoms_list:
        raise ValueError("No conformers with correct connectivity")
    
    saved = []
    k = 0
    n_min = min(n_samples, len(atoms_list))
    charge = Chem.GetFormalCharge(og_mol)
    while k < n_min:
        atoms = random.choice(atoms_list)
        if atoms not in saved:
            write(os.path.join(output_path, f"{basename}_conformer_{k}_charge_{charge}.xyz"), atoms, format="xyz")
            saved.append(atoms)
            k += 1

"""
Helper functions
"""
def remove_charge(mol):
    for atom in mol.GetAtoms():
        if atom.GetFormalCharge() != 0:
            atom.SetFormalCharge(0)           
    return mol

def relabel_stars(smiles):
    smiles = smiles.replace('[*]', '*')
    return smiles.replace("*", "[Au]")

def is_charged(mol):
    return any(atom.GetFormalCharge() != 0 for atom in mol.GetAtoms())

def get_rdkit_mol(ase_atoms):
    with NamedTemporaryFile(suffix=".xyz") as tmp:
        write(tmp.name, ase_atoms, format="xyz")
        obmol = next(pybel.readfile("xyz", tmp.name))
        
    obmol.OBMol.ConnectTheDots()
    obmol.OBMol.PerceiveBondOrders()
    molblock = obmol.write("mol")

    mol = Chem.MolFromMolBlock(molblock, sanitize=False)
    
    ase_atoms = [atom.number for atom in ase_atoms]
    rdkit_atoms = [atom.GetAtomicNum() for atom in mol.GetAtoms()]

    assert ase_atoms == rdkit_atoms, "Atom types do not match between ASE and RDKit"
    return mol

def remove_bond_orders(mol):
    mol = Chem.RWMol(mol)  # make editable
    for bond in mol.GetBonds():
        # set all bonds to SINGLE
        bond.SetBondType(Chem.BondType.SINGLE)
    return mol.GetMol()

def has_right_connectivity(conf, og_mol):
    mol2 = get_rdkit_mol(conf)
    mol1 = Chem.AddHs(og_mol)

    mol1 = remove_charge(remove_bond_orders(mol1))
    mol2 = remove_charge(remove_bond_orders(mol2))

    return mol1.HasSubstructMatch(mol2) and mol2.HasSubstructMatch(mol1)
    
"""
Main
"""
def main(smiles_bank, smiles_dir, working_dir, loqi_path, n_samples=10):
    log_smiles = os.path.join(working_dir, "all_smiles.csv")
    i = 0
    n_loops = 0
    while i < n_samples:
        smiles = make_branched(smiles_bank=smiles_bank,
                               copolymer=random.choice([True, False]),
                               working_dir=smiles_dir,
                               max_atoms=150)

        clean_smiles = Chem.MolToSmiles(Chem.RemoveHs(Chem.MolFromSmiles(smiles)))
        if os.path.isfile(log_smiles):
            current_smiles = pd.read_csv(log_smiles, header=None)[0]
            if clean_smiles in current_smiles:
                # don't keep the same polymer if already run
                n_loops += 1
                continue

        sdf = run_loqi(smiles, i, working_dir, loqi_path)
        if not sdf: 
            # if no sdf produced, skip
            n_loops += 1
            continue
            
        output_path = os.path.join(working_dir, "xyzs/")
        try:
            prune_confs(sdf, smiles, output_path, n_samples=10)
        except ValueError as e: # don't save bad conformers
            print(f"ERROR: No connected conformers for {clean_smiles}")
            n_loops += 1
            continue
        
        print(f"Saved 10 conformers for {clean_smiles}")
        with open(log_smiles, 'a') as file:
            file.write(f"{clean_smiles}\n")
        
        i += 1
        n_loops += 1

        if n_loops > (n_samples * 2): 
            break
            
    
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--smiles_bank", default=None)
    parser.add_argument("--smiles_dir", default="")
    parser.add_argument("--working_dir", default=".")
    parser.add_argument("--loqi_path", default=".")
    parser.add_argument("--n_samples", type=int, default=10)
    
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    main(args.smiles_bank, args.smiles_dir, args.working_dir, args.loqi_path, n_samples=args.n_samples)

    
    